[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "json-extract-polars"
version = "0.1.2"
authors = [
  { name="Vatsa", email="228140210+svr-s@users.noreply.github.com" },
]
description = "A powerful Python utility designed to natively flatten, parse, and filter deeply nested JSON data into clean, normalized Polars DataFrames using lazy evaluation for extreme performance."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "polars>=0.20.0",
    "pyyaml>=6.0",
    "json5>=0.9.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/svr-s/json_extract_polars"
Issues = "https://github.com/svr-s/json_extract_polars/issues"
